name: Build nightly container image
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
permissions:
  contents: read
  packages: write

jobs:
  build-nightly-image:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - name: Log in to the Github Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate nightly version number
        id: version_vars
        run: |
          echo mastodon_nightly_version=nightly-$(TZ="Etc/UTC" date +'%Y-%m-%d') >> $GITHUB_OUTPUT

      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: |
            ghcr.io/mastodon/mastodon
          flavor: |
            latest=auto
          tags: |
            type=raw,value=nightly
            type=schedule,pattern=${{ steps.version_vars.outputs.mastodon_nightly_version }}
          labels: |
            org.opencontainers.image.description=Nightly build image used for testing purposes

      - uses: docker/build-push-action@v4
        with:
          context: .
          # The version suffix needs the plus character here so that it reads as
          # v4.1.2+nightly-2022-03-05 instead of v4.1.2nightly-2022-03-05
          build-args: MASTODON_VERSION_SUFFIX=+${{ steps.version_vars.outputs.mastodon_nightly_version }}
          platforms: linux/amd64,linux/arm64
          provenance: false
          builder: ${{ steps.buildx.outputs.name }}
          push: ${{ github.repository == 'mastodon/mastodon' && github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
